### ISSUE TITLE
Make organization names more prominent

### ISSUE THREAD

**Issue by mackh** [PeaceGeeksSociety/servicesadvisor-3.0#101]
https://www.evernote.com/l/AAht5hDbIM5OCL4zi7YfPrmmr_sH0H7jzk8

The name of organizations is hard to see

**Comment by smithmilner** [comment]
Moved the organization name to be right aligned with the logo.
![Moved org name to the right above logo](http://skitch.affinity02.ct.coop/Services_Advisor-20170725-144550.jpg)

**Comment by PeaceGeeksProjects** [comment]
Verified on Test
