### ISSUE TITLE
Update build process

### ISSUE THREAD

**Issue by smithmilner** [PeaceGeeksSociety/servicesadvisor-3.0#102]
Updating the build process to remove committed libraries and improve our toolset.

**Comment by smithmilner** [comment]
Hi Magdi. The frontend build process has been updated. If everything goes well there should be no difference for you. Can you confirm that is true please.

**Comment by PeaceGeeksProjects** [comment]
Yes, I can get into the Client App Now...  However, the 3 text fields (Addit'l Details, Public Address, & Comments) do not show on the Nodes or on the Map Pop-out.

**Comment by PeaceGeeksProjects** [comment]
Has the fix for the Text fields been deployed to the Test site?
I C that the Turkey site is fixed.  But not the Test site yet.

**Comment by smithmilner** [comment]
Yes this was fixed. The map defaults to Somali though which is still blank because there is no text translations for it. If you added comments in the somali version of node 36 Or if you switch the map to english you will see it.

**Comment by PeaceGeeksProjects** [comment]
Verified on Test
