### ISSUE TITLE
Make marker cluster colours configurable.

### ISSUE THREAD

**Issue by smithmilner** [PeaceGeeksSociety/servicesadvisor-3.0#104]
The current clustering scheme of green/orange/red doesn't make sense here. Change the clustering colours to be configurable.

**Comment by smithmilner** [comment]
Added configuration which allows us to change the colours of clusters. The default clustering is categorized into three groups:

- small (less than 10 markers)
- medium (less than 100 markers)
- large (more than 100 markers)

We are also able to control the text colour and the outer partially transparent border on the marker.

![example](http://skitch.affinity02.ct.coop/defaultsettings.js_%E2%80%94_services-advisor-20170721-144040.jpg)

**Comment by smithmilner** [comment]
I've changed the test site to have pink clusters as an example that it's configurable. Please confirm.

**Comment by smithmilner** [comment]
Here is an example of the Turkey data with flat cluster colours ![example](http://skitch.affinity02.ct.coop/Services_Advisor-20170721-145804.jpg)

**Comment by PeaceGeeksProjects** [comment]
Test is now pinkish :)
Can we make that config visible to Managers?

**Comment by smithmilner** [comment]
Unfortunately it's just available on the map front end. There is no way to pass configuration from the Drupal site forward right now. I see that being a standalone ticket and we could add other configurables to it as well. (map tiles, languages, disabled fields)

**Comment by PeaceGeeksProjects** [comment]
@mackh @PeaceGeeks would this great idea be done in the SA-Globalization or in the Pathways Project?

**Comment by mackh** [comment]
We should consider this as a feature in the pathways project, I'm hoping to
limit the amount of new features in the SA prototype

-M
