### ISSUE TITLE
Improve the Language Selector

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/servicesadvisor-3.0#14]
It should show whatever Language is 'selected' maintaining the translations as in the picklist.

**Comment by mackh** [comment]
please provide more details and an example on this ticket

**Comment by PeaceGeeksProjects** [comment]
@mackh I showed it to @smithmilner yesterday in the Skype chat.  Here is a pic...
![14](https://cloud.githubusercontent.com/assets/16202351/18973569/ffe0b5c6-8652-11e6-8018-d3b4b8e13fd1.jpg)
and here is his comment:
> "You're right that it's not consistent. We should probably put some thought into the UX of that switcher.For example:

> An  english speaker who somehow got stuck on the arabic language needs to see a way to get back to english."

**Comment by PeaceGeeksProjects** [comment]
Verifed!

**Comment by mackh** [comment]
We need to figure out the best practice for indicating that the language switcher is what you are looking for, if you are English speaking in an Arabic interface, how do you know that you should change the selector?

**Comment by PeaceGeeksProjects** [comment]
Here are some ideas from the web:
http://www.flagsarenotlanguages.com/blog/best-practice-for-presenting-languages/
http://ux.stackexchange.com/questions/2472/how-to-graphically-represent-a-language
https://competition.adesignaward.com/design.php?ID=22868
http://wplang.org/never-use-flags-language-selection/

**Comment by PeaceGeeksProjects** [comment]
Verified on Test
