### ISSUE TITLE
Fix the image upload icon for partner profiles

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/servicesadvisor-3.0#15]
<img width="717" alt="screen shot 2016-09-29 at 3 27 30 pm" src="https://cloud.githubusercontent.com/assets/2263033/18975884/6581bb78-8662-11e6-9c74-1be795d3d0fd.png">

**Comment by smithmilner** [comment]
There were 2 problems that caused this. One involved the code and caused on all installs while the other varies by instance. Once the code change is rolled out we should confirm it's fixed on all sites.

**Comment by PeaceGeeksProjects** [comment]
see also #26
