### ISSUE TITLE
Fix URL  .../admin/content

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/servicesadvisor-3.0#17]
This URL now goes to the landing page...  We should allow Site Administrators to view the contents and be able to use the Standard Drupal Admin view for Content, Users, & Taxonomy.  Here is what is in the Users Manual for SA:

The Site Administrators functions are detailed in the following sections.  They can:
Manage Users - using the <base>/admin/people URL.
Manage Organizations  - using the <base>/admin/content URL.
Manage Taxonomies - using the <base>/admin/structure/taxonomy  URL

Users & Taxonomies link work fine.  Please fix the content one.

This is an alternative to #3

**Comment by mackh** [comment]
Smith - we should decide if we want to go this way or use admin menu for this

**Comment by smithmilner** [comment]
Access in general needed a review. I think this is the way to go instead of #3. With better access rules it should be much cleaner and simpler for site managers anyway.

**Comment by PeaceGeeksProjects** [comment]
Issue #3 is the solution implemented.  Closing...
