### ISSUE TITLE
Enforce Admin (User1) to 'own' ALL Groups

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/servicesadvisor-3.0#18]
This is done on import.  We need to enforce it when users create an Organization Manually.  This will prevent Site Admins home page to be 'cluttered' by all the Organizations they created by adding the Service Partners...

**Comment by mackh** [comment]
Goal here is to keep Site Administrators from being a default member of groups they create.

**Comment by smithmilner** [comment]
I have decided to make the default author of new partners blank. This will prevent more crazy entries in the user listings and stop the clutter for the site managers.

**Comment by PeaceGeeksProjects** [comment]
Verified on Dev...
