### ISSUE TITLE
Add default Office hours

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/servicesadvisor-3.0#19]
e.g. Sun - Thu 9:00 5:00 with 2 hours siesta from 12:00 to 2:00

**Comment by smithmilner** [comment]
We now have the ability to set multiple default office hours. Please let me know what makes the most sense and I can featurize in some defaults.

**Comment by PeaceGeeksProjects** [comment]
Can you provide the 'Site Administrator' with the ability to set the defaults?

**Comment by PeaceGeeksProjects** [comment]
Closed the issue on the Somalia Github.  Verified on Test.
