### ISSUE TITLE
Can users add services across multiple sectors?

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/servicesadvisor-3.0#21]
Magdi please test 3.0 for both matters.

**Comment by PeaceGeeks** [comment]
Users can add activities across multiple sectors 
It takes approx 10 minutes for the record on the map to update
Once the record is updated, it uses the icons for the most recently added activity and not for the other activities. 
Also, on the map, the activities display properly in the pop-up preview (on the left/ map but not on the right any more - it did display here properly before the update)

**Comment by PeaceGeeks** [comment]
Also, admins seem to be able to select multiple orgs when adding records. Can we limit that?

**Comment by PeaceGeeksProjects** [comment]
With the ease of 'cloning' I strong;y suggest to LIMIT each Service to ONE Sector.
