### ISSUE TITLE
Remove paging for Taxonomy list

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/servicesadvisor-3.0#25]
see https://github.com/PeaceGeeksSociety/ServicesAdvisor-2.0/issues/45

**Comment by smithmilner** [comment]
It's not possible to remove paging entirely but I set it to an absurd 1,000 terms per page. Which should effectively remove the pager for us.

**Comment by PeaceGeeksProjects** [comment]
Verified on Test
