### ISSUE TITLE
Error when uploading a Logo for a Service Provider

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/servicesadvisor-3.0#26]
![image](https://cloud.githubusercontent.com/assets/16202351/22489416/41ceedec-e7cc-11e6-9caf-eb16e8d0b907.png)

**Comment by PeaceGeeksProjects** [comment]
see also #15

**Comment by smithmilner** [comment]
The warning has to do with each environment so it's possible for some installs to be fixed while others aren't. I'll deal with this during next roll out. The issue specified in #15 has been fixed.

**Comment by PeaceGeeksProjects** [comment]
Verified in Test
