### ISSUE TITLE
Node Name missing the Node Num

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/servicesadvisor-3.0#27]
the PG node was created today...
http://admin.test.servicesadvisor.org/
![image](https://cloud.githubusercontent.com/assets/16202351/22490680/6ecbc1ba-e7d3-11e6-8c7c-8cff47800b11.png)

**Comment by smithmilner** [comment]
Unfortunately there is no way to do this in real time. I had to create a queue which runs during cron and adds the NID to the title.

**Comment by smithmilner** [comment]
Confirmed cron is configured to run every 5min on the test site.

**Comment by PeaceGeeksProjects** [comment]
@smithmilner Please review the logic.  It 'looks like' it is missing some Somali nodes (e.g. nodes 28 & 34)...  May be we can add the language code to the node name as well so that they do not appear 'duplicate' on the list?

![image](https://cloud.githubusercontent.com/assets/16202351/22937926/f6004ef6-f28e-11e6-9866-798ca0329da3.png)

**Comment by smithmilner** [comment]
@PeaceGeeksProjects ah I should've advised that this solution works for new nodes and won't update retroactively. Old node titles are fixed by simply resaving them.

**Comment by PeaceGeeksProjects** [comment]
Verified in Test
