### ISSUE TITLE
Provide the 'Site Administrator' with the ability to set the Office Hours Defaults

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/servicesadvisor-3.0#28]
Currently one default is hard coded "All day with 1 hour break"

**Comment by smithmilner** [comment]
The Office Hour defaults are a field setting. Which means all installs will share the settings. The best course of action would be to come up with a sensible set of defaults they can all use. Please advise.

**Comment by PeaceGeeksProjects** [comment]
How about:
7 days 1 hour break (as currently set)
7days no break
potentially repeating the pair (break & No break) for
6 days Fri off
6 days Sun off
5 days Fri/Sat Off
5 days Sat/Sun off
etc.
or is that overkill???

**Comment by smithmilner** [comment]
I've added a 7 days no break preset as well. I'm hoping they can be tweaked from there. I want to be careful of adding too many buttons and cluttering the UI. It's possible to add more though.

**Comment by PeaceGeeksProjects** [comment]
Verified On Test.  Tx @smithmilner 

I would strongly suggest to replace 'Full Days' with '7 Days'..
