### ISSUE TITLE
Cannot edit  Taxonomy Term

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/servicesadvisor-3.0#29]
Error when clicking on any term e.g. http://admin.test.servicesadvisor.org/admin/structure/taxonomy/service_accessibility
May be related to #8 

![image](https://cloud.githubusercontent.com/assets/16202351/22513605/974b60cc-e851-11e6-85a3-f214c682a087.png)

**Comment by smithmilner** [comment]
This was due to a bug with node_view_permissions module. It's since been patched.

**Comment by PeaceGeeksProjects** [comment]
Verified in Test
