### ISSUE TITLE
'simplify and correct' the Site Admin Menu

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/servicesadvisor-3.0#3]
It should simply be: Content, People (Users), & Taxonomy (Picklists)
![3](https://cloud.githubusercontent.com/assets/16202351/18481778/5894291e-7992-11e6-8f66-169c973053bb.JPG)

**Comment by PeaceGeeksProjects** [comment]
@mackh This has become important now that we are implementing Turkey.  The Site Admin need the 'Content' link to Add Groups and view all contents.  Also, I am doing the documentation and would like a 'clean' screen shot with only the relevant info for them
i.e. please get rid of Add Content, Configuration  and Reports on the top black admin menu
I can live with Structure but I would prefer to go directly to Taxonomy if easily done.

**Comment by smithmilner** [comment]
I believe #17 is the way to go.

**Comment by PeaceGeeksProjects** [comment]
Need to get rid of the 'Configuration' item on the Menu

**Comment by smithmilner** [comment]
I've removed items under the configuration menu tree for the Manager Role.

**Comment by PeaceGeeksProjects** [comment]
Verified in Test
