### ISSUE TITLE
Site Email needs to be reset

### ISSUE THREAD

**Issue by mackh** [PeaceGeeksSociety/servicesadvisor-3.0#32]
Currently the site email is set to admin@example.com

It should be set to no-reply@servicesadvisor.org

**Comment by PeaceGeeksProjects** [comment]
@mackh Site manager does not have access to that field.  Should they? what is it used for?

Cannot verify this.

**Comment by smithmilner** [comment]
@PeaceGeeksProjects It's the email address used when Drupal sends an email out. It can be confirmed here /admin/config/system/site-information but it's not available for managers only administrators.

**Comment by PeaceGeeksProjects** [comment]
@smithmilner yep, that is why I cannot verify...  @mackh is the one that has toi verify and close that one.

**Comment by PeaceGeeksProjects** [comment]
Verified on Tutkey
