### ISSUE TITLE
Intake Criteria Comments field missing?

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/servicesadvisor-3.0#35]
![image](https://cloud.githubusercontent.com/assets/16202351/22944971/6a48e0ee-f2a7-11e6-9285-237ee25fb002.png)

**Comment by smithmilner** [comment]
@PeaceGeeksProjects I misread this ticket the first time. I'm not familiar with there being a comment field for Intake Criteria. Did it exist before or was it requested?

**Comment by PeaceGeeksProjects** [comment]
This is a question to @PeaceGeeks & @mackh .  I just swa a reference to a comment field in the list...
![image](https://cloud.githubusercontent.com/assets/16202351/23366048/388c9826-fcba-11e6-810d-530b156046a4.png)

**Comment by mackh** [comment]
Hi - just to clarify here, the Comments means the global comments field for
the record, there is no additional text area that is specifically for
Intake requirements.
