### ISSUE TITLE
Extra label in Add/Edit Service

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/servicesadvisor-3.0#37]
![image](https://cloud.githubusercontent.com/assets/16202351/22952288/375ed304-f2c1-11e6-975e-9fc5649922e9.png)

**Comment by smithmilner** [comment]
That fieldset allows content authors to set translations are outdated. It should be used if there is a major change in the content.

**Comment by PeaceGeeksProjects** [comment]
Tx @smithmilner ...  It just did not expand when I clicked on the arrow beside it.  It expanded when I click on the title though.  May be we can default it to expanded?
