### ISSUE TITLE
Admin App: Users should not be able to Delete Organizations

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/servicesadvisor-3.0#39]
That should only be done by Managers?
![image](https://cloud.githubusercontent.com/assets/16202351/22955785/fd95c9d6-f2d2-11e6-91e4-6f55e53c5f03.png)

**Comment by mackh** [comment]
Why Managers only?  I guess it should not allow the org to be deleted if it contains records in either case.

**Comment by PeaceGeeksProjects** [comment]
I fully agree Orgs should not be deleted if they have any 'Services'.  In general, SA Managers are the ones controlling the 'partner' relationship.  SA users should be limited to add/modify services for their Org. I suggest that SA users should not be allowed to delete their org.

**Comment by PeaceGeeksProjects** [comment]
@mackh @smithmilner Could we have a final decision on that.  I propose that Managers are the creators/'deletors' of Orgs.  Org Admins are only editors of orgs. aal org members can add services for their orgs.
