### ISSUE TITLE
Show the 'Public Address' field on the Client App record

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/servicesadvisor-3.0#42]
![image](https://cloud.githubusercontent.com/assets/16202351/23135406/5e765bd4-f74d-11e6-853c-577bb29af156.png)

![image](https://cloud.githubusercontent.com/assets/16202351/23135439/865d805a-f74d-11e6-9300-f54aa2a1e399.png)

**Comment by fmann** [comment]
This involves changes to both the front end and the backend.  Both are up on the testing sites.

**Comment by PeaceGeeksProjects** [comment]
Verified on Test
