### ISSUE TITLE
Client App: Hide middle levels in nested Categories - Configurable

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/servicesadvisor-3.0#48]
Let Managers decide.

See also: https://github.com/PeaceGeeksSociety/SA-UNHCR-Turkey/issues/23

Example of 'crowded' Service:
![48a](https://cloud.githubusercontent.com/assets/16202351/23306004/35559dc6-fa56-11e6-9a74-a84cfe1879b8.png)
![48b](https://cloud.githubusercontent.com/assets/16202351/23306006/355c1bec-fa56-11e6-8458-2d3cd1794191.png)

**Comment by smithmilner** [comment]
I have changed the services provided information to only show root and leaf items.

**Comment by PeaceGeeksProjects** [comment]
Tx @smithmilner However, it only shows that for the 1st service only.  Shouldn't it show for each service of the multi service location?  or is this a different issue for Multi Service nodes?  I see that Client App filters also do not work for the other services (health in this case)
![image](https://cloud.githubusercontent.com/assets/16202351/25725257/04be220a-30d4-11e7-8366-c0801e9a34d0.png)

**Comment by smithmilner** [comment]
I haven't changed anything on the Drupal site other than the json feed. You won't see any changes there. I'm just removing the middle level categories.

![services advisor](https://cloud.githubusercontent.com/assets/410197/25728502/6159f290-30e4-11e7-9066-6782452809af.jpg)

**Comment by PeaceGeeksProjects** [comment]
Verified in Test
