### ISSUE TITLE
Admin App: Enhance the switch back link for Masquerade

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/servicesadvisor-3.0#49]
So that it is more obvious how Managers Go back to being themselves

**Comment by smithmilner** [comment]
I've added a message that displays on every pageload while masquerading. There is a link to switchback in the message.

http://skitch.affinity02.ct.coop/All_Services_%7C_Services_Advisor_Jordan-20170421-154412.jpg

**Comment by PeaceGeeksProjects** [comment]
Verified on Test
