### ISSUE TITLE
Masquerade logic is broken

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/servicesadvisor-3.0#50]
When I select Masquerade as a user, my account stays the same and the landing page appears.

Not working in the previous version either... e.g. Turkey error
![image](https://cloud.githubusercontent.com/assets/16202351/23241563/8408461e-f928-11e6-8e52-8bc84edf1718.png)

Still works on Jordan

**Comment by smithmilner** [comment]
@PeaceGeeksProjects I have done a set of deployments for Turkey. Can you check if the issue persists?

**Comment by PeaceGeeksProjects** [comment]
@smithmilner Fixed on Turkey...
