### ISSUE TITLE
Admin App: Add a 'Type' field for the Service Partner

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/servicesadvisor-3.0#52]
Partner type: Government services;Municipal services;UN Agency;INGO;NGO; Civil Society (6 values)
Requested by Richard Shdeed
see also https://github.com/PeaceGeeksSociety/SA-UNHCR-Turkey/issues/28

If there are no terms in this vocabulary, do not show on form

**Comment by mackh** [comment]
8 hours estimated

**Comment by mackh** [comment]
Add to main backend search
Add single term selection only
Accommodate this field in bulk upload

**Comment by fmann** [comment]
This is on the test server now. PG has been tagged as INGO.

**Comment by PeaceGeeksProjects** [comment]
Verified on Test
