### ISSUE TITLE
Client App: Hide 'Closed Days'

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/servicesadvisor-3.0#56]
Only show selected days & hours

see also https://github.com/PeaceGeeksSociety/SA-UNHCR-Turkey/issues/26

**Comment by smithmilner** [comment]
Here is an example location with Saturday and Sunday closed. http://test.servicesadvisor.org/#/services/27?hideOthers=false

**Comment by PeaceGeeksProjects** [comment]
Verified on Test
