### ISSUE TITLE
Client App: add 'printable' view

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/servicesadvisor-3.0#61]
see https://github.com/PeaceGeeksSociety/SA-UNHCR-Turkey/issues/31

**Comment by fmann** [comment]
This is on the test site now.

**DEPLOYMENT NOTES**

Two steps were required to get this working on the test site.

1. First I had to run `npm install --save https://github.com/gilf/ngPrint.git` to get the library to install. Oddly nothing changed in the package.json, but it works now.

2. Then I had to run `gulp` to recompile the app.js.

**Comment by PeaceGeeksProjects** [comment]
I think the Print layout needs improvement.  Can it be similar to the Admin App one?

**Comment by fmann** [comment]
For initial release we're going to go w/ the current display.

**Comment by PeaceGeeksProjects** [comment]
I do not think this is useful or user friendly.  However, this is verified in Test.

**Comment by fmann** [comment]
The install issue has been fixed.
