### ISSUE TITLE
Limit zoom

### ISSUE THREAD

**Issue by smithmilner** [PeaceGeeksSociety/servicesadvisor-3.0#71]
We need configurable maximum bounds for panning and zooming for both Drupal and the frontend.

Limit zoom on map to one planet worth, no need to limit to a local bounding box

**Comment by PeaceGeeksProjects** [comment]
@Smtih on the Client App, the limit is a couple of continents worth.  On theAdmin App, the limit is 3.5 planets worth :)
![image](https://cloud.githubusercontent.com/assets/16202351/25295692/732de6de-2699-11e7-855a-8078bf576055.png)
![image](https://cloud.githubusercontent.com/assets/16202351/25295726/a12fa13a-2699-11e7-9122-b540c23b904f.png)

**Comment by smithmilner** [comment]
I've added configuration to the Drupal side as well now. I'm happy with it showing a couple continents like the frontend. We don't want to see the Earth wrapped repeatedly though.

**Comment by PeaceGeeksProjects** [comment]
Verified on Test.
