### ISSUE TITLE
AR cash icon breaks

### ISSUE THREAD

**Issue by smithmilner** [PeaceGeeksSociety/servicesadvisor-3.0#72]
https://www.evernote.com/l/AAgKdtNeK7VMf5JIUyC_S2pCRe1Dmuxy5mQ

**Comment by smithmilner** [comment]
We should switch to use a different icon that matches the rest.

**Comment by smithmilner** [comment]
Changed the cash icon to match the others http://turkey.servicesadvisor.org/#/?language=AR

**Comment by PeaceGeeksProjects** [comment]
It does not show at all...  The cash line is just weird in AR???
![image](https://cloud.githubusercontent.com/assets/16202351/25294988/854785bc-2696-11e7-8474-3e6652c0849e.png)

**Comment by smithmilner** [comment]
It's at the bottom in Arabic because of their alphabet but it's there. http://skitch.affinity02.ct.coop/Services_Advisor-20170421-164058.jpg

**Comment by PeaceGeeksProjects** [comment]
Verified on Turkey
