### ISSUE TITLE
Partner Author anonymous

### ISSUE THREAD

**Issue by smithmilner** [PeaceGeeksSociety/servicesadvisor-3.0#76]
Node add partner defaults to Anonymous
we should be setting the partner owner manually on Partner node create

**Comment by smithmilner** [comment]
Making the partner author anonymous was a feature request earlier. I can expose the author field again while also have it be blank by default. This should be the best of both worlds.

**Comment by mackh** [comment]
Agreed.  Sounds good.

**Comment by PeaceGeeksProjects** [comment]
Can it stay blank?  If not, I would suggest default to 'Anonymous'...  Most Users would not know what to do...

**Comment by smithmilner** [comment]
Yeah we can leave it empty and it will default to anonymous.

**Comment by PeaceGeeksProjects** [comment]
Verified on Test
