### ISSUE TITLE
Edit Service Location Map Widget Duplicates.

### ISSUE THREAD

**Issue by smithmilner** [PeaceGeeksSociety/servicesadvisor-3.0#79]
A bug is making it possible to add multiple markers to the map. Currently the leaflet widget isn't removing markers properly so you can do this.

1. Add a marker to a blank map.
2. Remove the marker from the map.
3. Add 2 more markers to the map.

Steps 2 and 3 are repeatable.

Fix the leaflet widget so it tracks delete events properly so only 1 marker is ever added.

**Comment by smithmilner** [comment]
This has been fixed on test. Following the steps above you shouldn't be able to get to step 3 anymore.

**Comment by PeaceGeeksProjects** [comment]
Verified on Test
