### ISSUE TITLE
Admins do not have access to filtered html text format, taxo edit shows uneditable field

### ISSUE THREAD

**Issue by mackh** [PeaceGeeksSociety/servicesadvisor-3.0#8]
Masqurading as Murad (Murad Al-Samhouri) I cannot access the term description, because no users have access to the "Filtered HTML" text format, (which renders the WYSIWYG), but all the term descriptions are set to Filtered HTML. 

As an interim measure, I have updated the text format permission to allow admins to use it, but perhaps if would be better it taxo descriptions were set to use plain text globally.  Please review

**Comment by smithmilner** [comment]
Admins now have access to filtered HTML and a WYSIWYG however it looks like there is a bug between input filters and translations https://www.drupal.org/node/1030970 So the term descriptions don't get translated even though access has been fixed.

We're not using term descriptions for anything right now but it's something to be aware of.

**Comment by PeaceGeeksProjects** [comment]
Verified on Test
