### ISSUE TITLE
Move the “Additional details” field one section up #35

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/servicesadvisor-3.0#82]
See https://github.com/PeaceGeeksSociety/SA-UNHCR-Turkey/issues/35

**Comment by fmann** [comment]
On the edit screen this has been moved up right under the "Services Provided" area.

On the display screen it is now in the "General Information" section, right under "Organization."

**Comment by PeaceGeeksProjects** [comment]
Verified on Test
