### ISSUE TITLE
Language selection - frontend app

### ISSUE THREAD

**Issue by mackh** [PeaceGeeksSociety/servicesadvisor-3.0#85]
In the Frontend app we need to change to show dropdown in the speakers language, right now it shows English strings EN, AR etc

Use google translation to find the localized language string for each language so users can find the translation function

**Comment by PeaceGeeksProjects** [comment]
It is already working as requested in the Admin App
![image](https://cloud.githubusercontent.com/assets/16202351/26457688/efd8061e-4125-11e7-9dbf-17d3ed51848e.png)

**Comment by fmann** [comment]
This change is in.

**DEPLOY STEPS**
 - Pull the code
 - Update the site-specific-config.js to include two new key/value pairs for each supported language, the languageCode and display languageName. For example:

                "languageCode": "AR",
                "languageName": "العربية",

 - run `gulp`.

**Comment by PeaceGeeksProjects** [comment]
Somali is still somali rather than Soomaali (according to Google)
Could you also please add Arabic language to the site so that I can fully test.

**Comment by fmann** [comment]
There is no Arabic data on the test site, but you can see it in the language switcher now.

**Comment by PeaceGeeksProjects** [comment]
Verified on Test
