### ISSUE TITLE
Geocoder field doesn't replace old markers when new lat/lon is added

### ISSUE THREAD

**Issue by smithmilner** [PeaceGeeksSociety/servicesadvisor-3.0#93]
![geocoder field](http://skitch.affinity02.ct.coop/Create_Service_Location_%7C_Services_Advisor_Test-20170627-184629.jpg)
The geocoder field is not adding a new marker if the coordinates are changed. The desired behaviour is a page alert notifying the user that the map already has a marker on it and confirm they want to replace it with a new one. Once the alert is confirmed a new marker should replace the old one.

**Comment by PeaceGeeksProjects** [comment]
Not working for me.  see also #92
