### ISSUE TITLE
Client App: display the comment line & additional details field in the large right pane area

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/servicesadvisor-3.0#96]
In general the comment line is useful info for the refugees to consult.
Same for the additional details field
Requested by Turkey.

**Comment by smithmilner** [comment]
I have the new fields displaying on the frontend for the test site.
![Example](http://skitch.affinity02.ct.coop/Services_Advisor-20170712-190354.jpg)

**Comment by PeaceGeeksProjects** [comment]
Verified on Test
