### ISSUE TITLE
UNHCR Logo - "A Service Provided By:"

### ISSUE THREAD

**Issue by mackh** [PeaceGeeksSociety/servicesadvisor-3.0#99]
Add the text A Service Provided By:" and the UNHCR logo

Should look the same as http://data2.unhcr.org/en/situations/mediterranean

Also link the peacegeeks text to peacegeeks.org

**Comment by mackh** [comment]
https://www.evernote.com/l/AAjl5edd0exIwaMseC-Tq0df_qPZvxzTNAc

**Comment by PeaceGeeksProjects** [comment]
Verified on Test
